---
# description: Configure telegraf and get all relevent ec2 information

- name: Retrieve ec2 facts
  ec2_metadata_facts:
  when:
    - telegraf_agent_aws_tags

- name: Retrieve all ec2 tags on the instance
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    state: list
  when:
    - telegraf_agent_aws_tags
  register: ec2_tags

- name: "Copy the template for versions"
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_agent_config_path }}/telegraf.conf"
    owner: telegraf
    group: telegraf
    mode: 0640
  become: yes
  notify:
    - Restart Telegraf
    - Restart Telegraf container

- name: "Force restart service after reread config"
  meta: flush_handlers

- name: "Start Telegraf (If it wasn't running)"
  service:
    name: telegraf
    state: started
    enabled: yes
  become: yes
