---
# tasks file for ansible-telegraf

- name: "Install on RedHat"
  include_tasks: "RedHat.yml"
  
- name: "Configure Telegraf"
  include_tasks: "configure_linux.yml"
  when:
    - ansible_os_family != "Windows"
