---
# description: RedHat specific installation

- name: "RedHat | Set name if state == latest"
  set_fact:
    telegraf_agent_package: telegraf-{{ telegraf_agent_version }}
  when:
    - telegraf_agent_package_state != "latest"

- name: Use RHEL 7 packages for Fedora
  set_fact:
    telegraf_redhat_releasever: 7
  when:
    - ansible_distribution == "Fedora"

- name: "RedHat | Download Telegraf package (online)"
  get_url:
    url: https://s3-ap-southeast-1.amazonaws.com/zomato.infra/telegraf/telegraf-{{ telegraf_agent_version }}-1.x86_64.rpm
    dest: "{{ telegraf_agent_package }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: "RedHat | Install Telegraf package"
  package:
    name: "{{ telegraf_agent_package }}"
    state: "{{ telegraf_agent_package_state }}"
  register: is_telegraf_package_installed
  until: is_telegraf_package_installed is succeeded
  notify: "Restart Telegraf"